// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, ServiceStub, SmartBucket, SmartMemory, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  ACTIVITY_DB: SmartSql;
  ACTIVITY_MATCHER: ServiceStub<import('../activity-matcher/index.js').default>;
  ACTIVITY_MEDIA: SmartBucket;
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  CONVERSATION_MEMORY: SmartMemory;
  logger: Logger;
  mem: KvCache;
  tracer: Tracer;
  USER_DB: SmartSql;
  WEB_APP: ServiceStub<import('../web-app/index.js').default>;
}
