-- Activity Database Seed Data
-- 29 curated Indianapolis activities for retirees

INSERT INTO activities (
  id, name, description, category, location, venue,
  schedule_type, schedule_details, difficulty_level,
  social_size, cost, health_requirements, data_source
) VALUES
  -- FITNESS
  ('fit-001', 'Silver Sneakers Fitness Class', 'Low-impact group fitness class designed for active older adults. Includes strength training, cardio, and flexibility exercises.', 'fitness', 'Downtown Indianapolis', 'YMCA - Athenaeum', 'evergreen', 'Monday, Wednesday, Friday at 9:00 AM', 2, 'medium', 'low', 'Able to stand and move for 45 minutes', 'YMCA of Greater Indianapolis'),
  ('fit-002', 'Walking Group at Eagle Creek Park', 'Casual walking group meets for 2-mile walks around the scenic Eagle Creek reservoir. All fitness levels welcome.', 'fitness', 'Northwest Indianapolis', 'Eagle Creek Park', 'evergreen', 'Tuesday and Thursday at 8:30 AM', 1, 'medium', 'free', 'Able to walk on paved trails', 'Indy Parks & Recreation'),
  ('fit-003', 'Tai Chi in the Park', 'Gentle tai chi sessions in Garfield Park. Improves balance, flexibility, and inner peace. Instructor provided.', 'fitness', 'South Indianapolis', 'Garfield Park Sunken Garden', 'evergreen', 'Saturday at 7:30 AM (weather permitting)', 1, 'medium', 'free', 'Able to stand for 45 minutes', 'Garfield Park Conservatory'),
  ('fit-004', 'Aqua Aerobics', 'Water-based exercise class that is easy on joints. Great for those with arthritis or mobility concerns.', 'fitness', 'Broad Ripple', 'Broad Ripple Aquatic Center', 'evergreen', 'Monday, Wednesday, Friday at 10:00 AM', 2, 'medium', 'low', 'Comfortable in water, basic swimming ability helpful', 'Indy Parks & Recreation'),

  -- ARTS & CULTURE
  ('art-001', 'Indianapolis Museum of Art Tour', 'Guided tour of rotating exhibitions at Newfields. Includes gardens and outdoor art installations.', 'arts-culture', 'Midtown Indianapolis', 'Newfields (Indianapolis Museum of Art)', 'evergreen', 'Self-guided anytime during museum hours; guided tours Tuesday-Sunday at 2:00 PM', 2, 'small', 'medium', 'Moderate walking, seating available throughout', 'Newfields'),
  ('art-002', 'Indianapolis Symphony Orchestra Concert', 'World-class orchestral performances at the beautiful Hilbert Circle Theatre. Senior discounts available.', 'arts-culture', 'Downtown Indianapolis', 'Hilbert Circle Theatre', 'dated', 'Various dates, typically Friday and Saturday evenings', 1, 'large', 'medium', 'Able to sit for 2 hours with intermission', 'Indianapolis Symphony Orchestra'),
  ('art-003', 'Pottery Class at Garfield Park Arts Center', 'Beginner-friendly pottery throwing class. All materials provided. Create functional and decorative pieces.', 'arts-culture', 'South Indianapolis', 'Garfield Park Arts Center', 'evergreen', 'Tuesday at 1:00 PM, 6-week sessions', 2, 'small', 'low', 'Manual dexterity, able to sit for 2 hours', 'Garfield Park Arts Center'),
  ('art-004', 'Indiana History Center Exhibits', 'Explore Indiana history through interactive exhibits. Current special exhibition on Indiana during WWII.', 'arts-culture', 'Downtown Indianapolis', 'Indiana History Center', 'evergreen', 'Tuesday-Saturday 10:00 AM - 5:00 PM', 1, 'solo', 'low', 'Moderate walking', 'Indiana Historical Society'),

  -- VOLUNTEERING
  ('vol-001', 'Meals on Wheels Delivery', 'Deliver hot meals to homebound seniors in your neighborhood. Flexible schedule, meaningful connections.', 'volunteering', 'Various Indianapolis neighborhoods', 'Meals on Wheels of Central Indiana', 'evergreen', 'Weekday mornings, 9:30 AM - 12:00 PM, commit to one day per week', 2, 'solo', 'free', 'Valid driver''s license, able to carry meal containers', 'Meals on Wheels of Central Indiana'),
  ('vol-002', 'Reading Buddies at Local Elementary', 'Read with elementary students one-on-one to improve literacy. Background check required.', 'volunteering', 'Broad Ripple', 'Broad Ripple Elementary School', 'evergreen', 'Tuesday and Thursday, 2:00 PM - 3:00 PM during school year', 1, 'small', 'free', 'Able to sit and read aloud for 1 hour', 'Indianapolis Public Schools Volunteer Program'),
  ('vol-003', 'Habitat for Humanity Build Days', 'Help build affordable housing for families in need. Various tasks available for different abilities.', 'volunteering', 'Various Indianapolis locations', 'Habitat for Humanity of Indiana', 'dated', 'Saturday builds, 8:00 AM - 3:00 PM, sign up online', 3, 'large', 'free', 'Moderate physical activity, safety training provided', 'Habitat for Humanity of Indiana'),
  ('vol-004', 'Indianapolis Zoo Docent', 'Share your love of animals by leading tours and educating visitors. Training provided.', 'volunteering', 'West Indianapolis', 'Indianapolis Zoo', 'evergreen', 'Flexible shifts, minimum 4 hours per week', 2, 'medium', 'free', 'Comfortable walking and standing for extended periods', 'Indianapolis Zoo'),

  -- LEARNING
  ('learn-001', 'OLLI Lecture Series', 'Osher Lifelong Learning Institute offers university-level courses without exams. Topics include history, science, arts, and current events.', 'learning', 'IUPUI Campus', 'IUPUI - University Library', 'dated', 'Fall and Spring semesters, various times', 2, 'large', 'low', 'None', 'IUPUI OLLI'),
  ('learn-002', 'Computer Skills Workshop', 'Learn smartphone basics, social media, video calls, and online safety. Beginner-friendly.', 'learning', 'Downtown Indianapolis', 'Indianapolis Public Library - Central Branch', 'evergreen', 'Every other Wednesday at 2:00 PM', 1, 'small', 'free', 'None', 'Indianapolis Public Library'),
  ('learn-003', 'Local History Walking Tour', 'Guided walking tour of historic downtown Indianapolis. Learn about architecture, famous residents, and city development.', 'learning', 'Downtown Indianapolis', 'Indiana Landmarks Center', 'dated', 'First Saturday of each month at 10:00 AM', 2, 'medium', 'low', 'Able to walk 1-2 miles on sidewalks', 'Indiana Landmarks'),
  ('learn-004', 'Conversational Spanish Class', 'Beginner Spanish conversation group. Practice speaking in a low-pressure, friendly environment.', 'learning', 'Fountain Square', 'Fountain Square Library', 'evergreen', 'Thursday at 4:00 PM', 2, 'small', 'free', 'None', 'Indianapolis Public Library'),

  -- SOCIAL
  ('soc-001', 'Bridge Club', 'Friendly bridge games for all skill levels. Beginners welcome, instruction available.', 'social', 'Carmel (North Indianapolis)', 'Carmel Senior Center', 'evergreen', 'Monday and Friday at 1:00 PM', 1, 'medium', 'free', 'None', 'Carmel Clay Parks & Recreation'),
  ('soc-002', 'Coffee & Conversation Social', 'Casual morning meetup at local coffee shop. Discuss books, current events, or just chat with neighbors.', 'social', 'Broad Ripple', 'Coat Check Coffee', 'evergreen', 'Wednesday at 9:00 AM', 1, 'small', 'low', 'None', 'Broad Ripple Village Association'),
  ('soc-003', 'Indianapolis Hiking Club', 'Group hikes around central Indiana state parks and nature preserves. Carpools arranged.', 'social', 'Various locations around Indianapolis', 'Meetup coordination via email', 'dated', 'First and third Saturday each month, 9:00 AM', 3, 'medium', 'free', 'Able to hike 3-5 miles on trails', 'Indianapolis Hiking Meetup'),
  ('soc-004', 'Book Club at Barnes & Noble', 'Monthly book club discussing fiction and non-fiction. Book selections voted on by members.', 'social', 'Castleton (Northeast Indianapolis)', 'Barnes & Noble - Castleton', 'dated', 'Last Tuesday of each month at 6:30 PM', 1, 'medium', 'free', 'None', 'Barnes & Noble Events'),

  -- HOBBIES
  ('hob-001', 'Quilting Circle', 'Weekly quilting group for all skill levels. Bring your projects, share techniques, and enjoy community.', 'hobbies', 'Greenwood (South Indianapolis)', 'Greenwood Public Library', 'evergreen', 'Thursday at 10:00 AM', 2, 'small', 'free', 'Manual dexterity for needlework', 'Johnson County Public Library'),
  ('hob-002', 'Woodworking Workshop', 'Use fully-equipped woodshop to create projects. Training required for tool certification.', 'hobbies', 'Northeast Indianapolis', 'Indy Urban Acres', 'evergreen', 'Open shop hours: Tuesday, Thursday, Saturday 10:00 AM - 4:00 PM', 3, 'small', 'low', 'Able to safely operate power tools, standing for extended periods', 'Indy Urban Acres'),
  ('hob-003', 'Photography Club', 'Monthly photo walks and critique sessions. All camera types welcome, including smartphones.', 'hobbies', 'Various Indianapolis locations', 'Meeting locations rotate', 'dated', 'Second Saturday each month at 10:00 AM', 1, 'medium', 'free', 'Able to walk during photo outings', 'Indianapolis Photography Meetup'),
  ('hob-004', 'Community Garden Plot', 'Grow your own vegetables and flowers in a shared garden space. Tools and water provided.', 'hobbies', 'Fountain Square', 'Murphy Art Center Community Garden', 'evergreen', 'Access during daylight hours, April-October', 2, 'solo', 'low', 'Able to bend, kneel, and lift light objects', 'Indy Urban Acres'),
  ('hob-005', 'Chess Club', 'Play chess with fellow enthusiasts. All skill levels welcome, casual games and coaching available.', 'hobbies', 'Downtown Indianapolis', 'Indianapolis City Market', 'evergreen', 'Sunday at 2:00 PM', 2, 'small', 'free', 'None', 'Indianapolis Chess Club');
